sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
reviewed:
  npm:
    - "@fortawesome/fontawesome-common-types"
    - "@fortawesome/fontawesome-free"
    - "@fortawesome/fontawesome-svg-core"
    - "@fortawesome/free-brands-svg-icons"
    - "@fortawesome/free-regular-svg-icons"
    - "@fortawesome/free-solid-svg-icons"
    - "@sailshq/lodash"
    - "@webassemblyjs/helper-fsm"
    - "@webassemblyjs/leb128"
    - "@xtuc/ieee754"
    - addressparser
    - atob
    - bcrypt-pbkdf
    - bcryptjs
    - big.js-3.2.0
    - bl-2.2.1
    - bl-4.0.3
    - boom
    - cacache
    - caniuse-lite
    - color-convert-1.9.3
    - color-convert-2.0.1
    - colors
    - css-select
    - default-gateway
    - denque
    - detect-node
    - dom-serializer
    - domain-browser
    - electron-to-chromium
    - encoding
    - es6-templates
    - faye-websocket-0.11.3
    - figgy-pudding
    - font-awesome
    - formik
    - fs.realpath
    - glob
    - highlight.js
    - hoek
    - hoist-non-react-statics
    - http-proxy
    - ieee754
    - immutable-3.7.6
    - intl-format-cache
    - intl-messageformat
    - intl-messageformat-parser
    - jsbn
    - json-parse-even-better-errors
    - json-schema
    - json3
    - koa-lusca
    - lodash-4.17.19
    - lodash-4.17.20
    - lodash-es
    - lodash.deburr
    - lodash.includes
    - lodash.isboolean
    - lodash.isinteger
    - lodash.isnumber
    - lodash.isplainobject
    - lodash.isstring
    - lodash.once
    - lodash.throttle
    - mailcomposer
    - mdurl
    - nan
    - neo-async
    - node-addon-api
    - node-forge
    - nodemailer-fetch
    - nodemailer-shared
    - pako
    - path-browserify
    - path-is-inside
    - portfinder
    - qs-6.5.2
    - qs-6.7.0
    - rc
    - react-input-autosize
    - react-intl
    - react-transition-group-2.9.0
    - react-transition-group-4.4.1
    - readable-stream-2.3.7
    - readable-stream-3.6.0
    - readdirp-2.2.1
    - redux-immutable
    - retry
    - sanitize.css
    - sequelize-pool
    - serialize-javascript
    - sha.js
    - source-map-0.5.7
    - source-map-0.6.1
    - sprintf-js-1.0.3
    - sprintf-js-1.1.2
    - ssri
    - strapi
    - strapi-admin
    - strapi-connector-bookshelf
    - strapi-database
    - strapi-generate
    - strapi-generate-api
    - strapi-generate-controller
    - strapi-generate-model
    - strapi-generate-new
    - strapi-generate-plugin
    - strapi-generate-policy
    - strapi-generate-service
    - strapi-helper-plugin
    - strapi-plugin-content-manager
    - strapi-plugin-content-type-builder
    - strapi-plugin-email
    - strapi-plugin-upload
    - strapi-plugin-users-permissions
    - strapi-provider-email-sendmail
    - strapi-provider-upload-local
    - strapi-utils
    - string_decoder
    - synchronous-promise
    - terser
    - toposort-1.0.7
    - toposort-2.0.2
    - tslib
    - tty-browserify
    - typedarray
    - uglify-js
    - uri-js
    - urijs
    - wcwidth
    - webpack
    - webpack-dev-server
    - webpack-log
    - websocket-extensions
    - yargs
