sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
reviewed:
  npm:
    - "@fortawesome/fontawesome-common-types"
    - "@fortawesome/fontawesome-free"
    - "@fortawesome/fontawesome-svg-core"
    - "@fortawesome/free-brands-svg-icons"
    - "@fortawesome/free-regular-svg-icons"
    - "@fortawesome/free-solid-svg-icons"
    - "@sailshq/lodash"
    - "@webassemblyjs/helper-fsm"
    - "@webassemblyjs/leb128"
    - "@xtuc/ieee754"
    - addressparser
    - atob
    - bcrypt-pbkdf
    - bcryptjs
    - big.js
    - bl
    - boom
    - cacache
    - caniuse-lite
    - color-convert
    - colors
    - css-select
    - default-gateway
    - denque
    - detect-node
    - dom-serializer
    - domain-browser
    - electron-to-chromium
    - encoding
    - es6-templates
    - faye-websocket
    - figgy-pudding
    - font-awesome
    - formik
    - fs.realpath
    - glob
    - highlight.js
    - hoek
    - hoist-non-react-statics
    - http-proxy
    - ieee754
    - immutable
    - intl-format-cache
    - intl-messageformat
    - intl-messageformat-parser
    - jsbn
    - json-parse-even-better-errors
    - json-schema
    - json3
    - koa-lusca
    - lodash
    - lodash-es
    - lodash.deburr
    - lodash.includes
    - lodash.isboolean
    - lodash.isinteger
    - lodash.isnumber
    - lodash.isplainobject
    - lodash.isstring
    - lodash.once
    - lodash.throttle
    - mailcomposer
    - mdurl
    - nan
    - neo-async
    - node-addon-api
    - node-forge
    - nodemailer-fetch
    - nodemailer-shared
    - pako
    - path-browserify
    - path-is-inside
    - portfinder
    - qs
    - rc
    - react-input-autosize
    - react-intl
    - react-transition-group
    - readable-stream
    - readdirp
    - redux-immutable
    - retry
    - sanitize.css
    - sequelize-pool
    - serialize-javascript
    - sha.js
    - source-map
    - sprintf-js
    - ssri
    - strapi
    - strapi-admin
    - strapi-connector-bookshelf
    - strapi-database
    - strapi-generate
    - strapi-generate-api
    - strapi-generate-controller
    - strapi-generate-model
    - strapi-generate-new
    - strapi-generate-plugin
    - strapi-generate-policy
    - strapi-generate-service
    - strapi-helper-plugin
    - strapi-plugin-content-manager
    - strapi-plugin-content-type-builder
    - strapi-plugin-email
    - strapi-plugin-upload
    - strapi-plugin-users-permissions
    - strapi-provider-email-sendmail
    - strapi-provider-upload-local
    - strapi-utils
    - string_decoder
    - synchronous-promise
    - terser
    - toposort
    - tslib
    - tty-browserify
    - typedarray
    - uglify-js
    - uri-js
    - urijs
    - wcwidth
    - webpack
    - webpack-dev-server
    - webpack-log
    - websocket-extensions
    - yargs
    - minizlib
